import { collection, addDoc, getDocs, updateDoc, doc, query, where } from "firebase/firestore";
import { db } from "../firebase/config";
import dayjs from "dayjs";

export const processRecurringExpenses = async (uid, showSnackbar) => {
  try {
    const recurringRef = collection(db, "recurring_expenses");
    const q = query(recurringRef, where("uid", "==", uid));
    const snapshot = await getDocs(q);
    const now = dayjs();
    const todayStr = now.format("YYYY-MM-DD");

    snapshot.docs.forEach(async (recurringDoc) => {
      const data = recurringDoc.data();
      const nextDue = dayjs(data.nextDueDate);

      if (nextDue.isBefore(now, 'day') || nextDue.isSame(now, 'day')) {
        // It's due! Create transaction.
        const newTxn = {
          uid: uid,
          type: data.type,
          amount: data.amount,
          note: data.note,
          category: data.category,
          date: todayStr, // Add as today
          isAutoGenerated: true
        };

        await addDoc(collection(db, "transactions"), newTxn);

        // Calculate NEXT due date
        let nextDate = nextDue;
        if (data.frequency === "Weekly") nextDate = nextDate.add(1, 'week');
        else if (data.frequency === "Monthly") nextDate = nextDate.add(1, 'month');
        else if (data.frequency === "Yearly") nextDate = nextDate.add(1, 'year');

        // Update recurring doc
        await updateDoc(doc(db, "recurring_expenses", recurringDoc.id), {
          nextDueDate: nextDate.format("YYYY-MM-DD")
        });

        if (showSnackbar) {
          showSnackbar(`Auto-added recurring expense: ${data.note}`);
        }
      }
    });
  } catch (error) {
    console.error("Error processing recurring expenses:", error);
  }
};
